rails/config/routes.rb
Rails.application.routes.draw do
  # REST resources
  resources :notes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'notes#index'
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/note.rb
class Note < ApplicationRecord
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @note = Note.new(note_params)

    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    redirect_to notes_path
  end

  def edit
    @note = Note.find(params[:id])
  end

  def index
    @notes = Note.all
  end

  def new
    @note = Note.new
  end

  def show
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])

    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  private
    def note_params
      params.require(:note).permit(:note)
    end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/notes_helper.rb
module NotesHelper
end

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails/app/views/notes/edit.html.erb
<h1>Edit note</h1>

<%= form_with(model: @note) do |form| %>

  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:
      </h2>
      <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :note %><br>
    <%= form.text_field :note %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

rails/app/views/notes/index.html.erb
<h1>Listing notes</h1>

<%= link_to 'New note', new_note_path %>

<table>
  <tr>
    <th>Note</th>
  </tr>

  <% @notes.each do |note| %>
    <tr>
      <td><%= note.note %></td>
      <td><%= link_to 'Show', note_path(note) %></td>
      <td><%= link_to 'Edit', edit_note_path(note) %></td>
      <td><%= link_to 'Destroy', note_path(note), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

rails/app/views/notes/new.html.erb
<h1>New note</h1>

<%= form_with scope: :note, url: notes_path, local: true do |form| %>
  <p>
    <%= form.label :note %><br>
    <%= form.text_field :note %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', notes_path %>

rails/app/views/notes/show.html.erb
<p>
  <strong>Note:</strong>
    <%= @note.note %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %>
<%= link_to 'Back', notes_path %>